"""
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s, t):
        # Solution 1: self
        # dic = {}

        # for each in s:
        #     dic[each] = dic.get(each, 0) + 1

        # for each in t:
        #     if each not in dic or dic[each] == 0:
        #         return each

        #     else:
        #         dic[each] -= 1

        # Solution 2: self, faster

        # for each in s:
        #     t = t.replace(each, "", 1)
        # return t

        # Solution 3: sort

        # s = sorted(s)
        # t = sorted(t)

        # for i, j in enumerate(s):
        #     if j != t[i]:
        #         return t[i]

        # return t[-1]

        # Solution 4: using count, fastest

        # for i in t:
        #     if t.count(i) != s.count(i):
        #         return i

        # Solution 5: using counter, fastest

        from collections import Counter
        l = list(Counter(t) - Counter(s))
        return l[0]


sol = Solution()
s = "abcd"
t = "abcde"
print(sol.findTheDifference(s, t))
